### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by BraisGabin** [dst-academy/docker-steamcmd#12]
We don't have a tag for the docker image `0.3`. Probably a `RELEASING.md` file will help here.

**Comment by thasmo** [comment]
There is a tag, it's just not marked as a GitHub release. Or do I misunderstand?

**Comment by BraisGabin** [comment]
There is in deed. My bad. Any way: or add it like a release or remove the "versions" badge. I was confused for that reason.

**Comment by thasmo** [comment]
Added a release for `0.3.0` and used the same version naming scheme as for `dst-academy/docker-dontstarvetogether`.
